#spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/nutri_house
spring.datasource.username=root
spring.datasource.password=Francesco90
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
jwt.secret=b59781f11780b1cd5846920c0f6cebb25a4fe7040b4212da1ff9b7784dc77afe3d1ba75e027082c8c881ea132e0462b2a7eca5859450a63e5385b718084cf39c
jwt.expiration=3600000
